sudo: true

language: bash

services:
  - docker

env:
  global:
    - BRANCH="nixos-20.03"
    - GITHUB_ENDPOINT="netbootxyz/asset-mirror"
    - DEBIAN_FRONTEND="noninteractive"
    - BUILD_TYPE="direct_file"

branches:
  only:
    - 'nixos'
if: type != pull_request AND tag IS blank
script:
  - |
    export EXTERNAL_VERSION=$(curl -sL https://hydra.nixos.org/job/nixos/release-20.03/nixos.netboot.x86_64-linux/latest |awk -F '(/build/|/download/)' '/netboot.ipxe/ {print $2;exit}')
  - wget https://raw.githubusercontent.com/netbootxyz/build-pipelines/master/build.sh && chmod +x build.sh
  - git config --local user.name $GIT_USERNAME
  - git config --local user.email $GIT_EMAIL
  - export TRAVIS_TAG=${EXTERNAL_VERSION}-$(echo ${TRAVIS_COMMIT} | cut -c1-8)
  - ./build.sh compare ${TRAVIS_TAG} || travis_terminate 0
  - ./build.sh build ${BUILD_TYPE}
before_deploy:
# Tag this commit for release
  - git tag ${TRAVIS_TAG}
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: buildout/*
  skip_cleanup: true
  on:
    branch: $BRANCH
after_deploy:
  - ./build.sh endpoints $TRAVIS_TAG
after_success:
  - ./build.sh discord success
after_failure: 
  - ./build.sh discord failure
